name: CICD-AzureAppSer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  AZURE_WEBAPP_NAME: appcicdtest  
  AZURE_WEBAPP_PACKAGE_PATH: "."
  DOTNET_VERSION: "7.0.x"

jobs:

  avoid_reduncy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Redundant Build
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test app.test/app.test.csproj
      - name: Publish
        run: dotnet publish src/ -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp
      - uses: actions/upload-artifact@v3
        with:
          name: myapp
          path: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp
    
  deploy:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-22.04
    needs: build
    #environment:
      #name: "production"
      #url: ${{ steps.deploy-to-webapp.outputs.url }}
    
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: myapp
          path: myapp
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'